# Makefile generated by OpenModelica
# Platform: linux64

# Simulations use -O3 by default
CC=clang
CXX=clang++ -std=c++17
LINK=clang -shared
EXEEXT=
DLLEXT=.so
CFLAGS_BASED_ON_INIT_FILE=
# define OMC_CFLAGS_OPTIMIZATION env variable to your desired optimization level to override this
OMC_CFLAGS_OPTIMIZATION=-Os
DEBUG_FLAGS=$(OMC_CFLAGS_OPTIMIZATION)
CFLAGS= $(CFLAGS_BASED_ON_INIT_FILE) $(DEBUG_FLAGS) -DOM_HAVE_PTHREADS -fPIC -falign-functions -mfpmath=sse -fno-dollars-in-identifiers -Wno-parentheses-equality ${MODELICAUSERCFLAGS}   
CPPFLAGS= -I"/usr/bin/../include/omc/c" -I"/usr/bin/../include/omc" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=rPCR_03 -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=0 -DOMC_NUM_NONLINEAR_SYSTEMS=0 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0
# define OMC_LDFLAGS_LINK_TYPE env variable to "static" to override this
OMC_LDFLAGS_LINK_TYPE=dynamic
RUNTIME_LIBS= -Wl,--no-as-needed -Wl,--disable-new-dtags -lSimulationRuntimeC -llapack -lblas  -lm -lomcgc -lryu -lpthread -rdynamic -Wl,--no-undefined
LDFLAGS=-L"/usr/bin/../lib/x86_64-linux-gnu/omc" -L"/usr/bin/../lib" -Wl,-rpath,"/usr/bin/../lib/x86_64-linux-gnu/omc"  -Wl,-rpath,"/usr/bin/../lib"   $(RUNTIME_LIBS) 
DIREXTRA=-L"/scicore/home/sinnreic/kinter/openmodelica"
MAINFILE=rPCR_03.c
MAINOBJ=rPCR_03.o
CFILES=rPCR_03_functions.c rPCR_03_records.c \
rPCR_03_01exo.c rPCR_03_02nls.c rPCR_03_03lsy.c rPCR_03_04set.c rPCR_03_05evt.c rPCR_03_06inz.c rPCR_03_07dly.c \
rPCR_03_08bnd.c rPCR_03_09alg.c rPCR_03_10asr.c rPCR_03_11mix.c rPCR_03_12jac.c rPCR_03_13opt.c rPCR_03_14lnz.c \
rPCR_03_15syn.c rPCR_03_16dae.c rPCR_03_17inl.c rPCR_03_18spd.c 

OFILES=$(CFILES:.c=.o)
GENERATEDFILES=$(MAINFILE) rPCR_03.makefile rPCR_03_literals.h rPCR_03_functions.h $(CFILES)

.PHONY: omc_main_target clean bundle

# This is to make sure that rPCR_03_*.c are always compiled.
.PHONY: $(CFILES)

omc_main_target: $(MAINOBJ) rPCR_03_functions.h rPCR_03_literals.h $(OFILES)
	$(CC) -I. -o rPCR_03$(EXEEXT) $(MAINOBJ) $(OFILES) $(DIREXTRA)   $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)

omc_dll_target: $(MAINOBJ) rPCR_03_functions.h rPCR_03_literals.h $(OFILES)
	$(CC) -DOMC_DLL_MAIN_DEFINE -o $(MAINOBJ) -c $(MAINFILE) $(DIREXTRA)   $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
	$(CC) -shared -I. -o rPCR_03$(DLLEXT) $(MAINOBJ) $(OFILES) $(DIREXTRA)   $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)

clean:
	@rm -f rPCR_03_records.o $(MAINOBJ)

bundle:
	@tar -cvf rPCR_03_Files.tar $(GENERATEDFILES)