/* Additional record code for rPCR_03 generated by the OpenModelica Compiler OpenModelica 1.25.1~2-g175c5c9. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "rPCR_03_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

